---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
   - name: Install docker
     yum:
      name: docker
      state : present
     when : ansible_distribution == "CentOS"

   - name: Install docker on Ubuntu server
     apt: 
      name: docker
      state: present
     when: ansible_distribution == "Ubuntu"


   - name: Create user
     user:
      name: Axel
      comment: Axel Nana
