---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
   - name: Install tree
     yum:
      name: tree
      state : present
     when : ansible_distribution == "CentOS"

   - name: Install tree on Ubuntu server
     apt: 
      name: tree
      state: present
     when: ansible_distribution == "Ubuntu"


   - name: Create user
     user:
      name: Nana
      comment: Axel Nana
