---
-  hosts: all
   ignore_errors: yes
   become: yes
   tasks: 
    - name: Create user
      user: 
        name: Ngapmen
        comment: Ngapmen Michele

    - name: Create directory
      file: 
        path: /tmp/devop-ans
        owner: Ngapmen
        state: directory
        mode: 0777
        
    - name: Create file
      file:
        path: /tmp/ansible-ans
        owner: Ngapmen
        state: touch
        mode: 0600
